CREATE TABLE "neighborhood_demographics" (
    "nbhd_id" int,
    "nbhd_name" varchar,
    "population" int,
    "hispanic" int,
    "white" int,
    "black" int,
    "american_indian" int,
    "asian" int,
    "hawpacis" int,
    "other" int,
    "two_or_more" int,
    "housing_units" int,
    "occupied_units" int,
    "vacant_units" int,
    "male" int,
    "female" int,
    "age_0_to_9" int,
    "age_10_to_19" int,
    "age_20_to_29" int,
    "age_30_to_39" int,
    "age_40_to_49" int,
    "age_50_to_59" int,
    "age_60_to_69" int,
    "age_70_to_79" int,
    "age_80_plus" int,
    "households" int,
    "one_person_households" int,
    "two_or_more_person_households" int,
    "husb_wife_with_children" int,
    "male_with_children" int,
    "female_with_children" int,
    "mortgage" int,
    "owned_outright" int,
    "rented" int
);

CREATE INDEX ON "neighborhood_demographics" ("nbhd_id");
